[package]
name = "mios"
version = "0.1.0"
authors = ["Josh Hawkins <hawkins@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bootloader = "0.4.0"

[package.metadata.bootimage]
default-target = "x86_64-mios.json"
